PRINT LEFT$("HELLO WORLD", 5)
PRINT RIGHT$("HELLO WORLD", 5)
PRINT MID$("HELLO WORLD", 7, 5)
PRINT LEN("TEST")
PRINT CHR$(65)
PRINT ASC("A")
PRINT VAL("3.14")
PRINT STR$(42)
PRINT SPACE$(5)+"X"
PRINT STRING$(10, 42)
PRINT HEX$(255)
PRINT OCT$(255)
PRINT INSTR("HELLO WORLD", "WORLD")
PRINT "ABC" + "DEF"
