#include "tokens.h"
#include <stddef.h>
#include <string.h>

/*
 * Complete keyword table from IBMRES.ASM RESLST.
 * Sorted by token value for reverse lookup; the tokenizer
 * uses alphabetic lookup tables like the original.
 */
const keyword_entry_t gw_keywords[] = {
    /* Single-byte statement tokens */
    { "END",       TOK_END,       0 },
    { "FOR",       TOK_FOR,       0 },
    { "NEXT",      TOK_NEXT,      0 },
    { "DATA",      TOK_DATA,      0 },
    { "INPUT",     TOK_INPUT,     0 },
    { "DIM",       TOK_DIM,       0 },
    { "READ",      TOK_READ,      0 },
    { "LET",       TOK_LET,       0 },
    { "GOTO",      TOK_GOTO,      0 },
    { "RUN",       TOK_RUN,       0 },
    { "IF",        TOK_IF,        0 },
    { "RESTORE",   TOK_RESTORE,   0 },
    { "GOSUB",     TOK_GOSUB,     0 },
    { "RETURN",    TOK_RETURN,    0 },
    { "REM",       TOK_REM,       0 },
    { "STOP",      TOK_STOP,      0 },
    { "PRINT",     TOK_PRINT,     0 },
    { "CLEAR",     TOK_CLEAR,     0 },
    { "LIST",      TOK_LIST,      0 },
    { "NEW",       TOK_NEW,       0 },
    { "ON",        TOK_ON,        0 },
    { "WAIT",      TOK_WAIT,      0 },
    { "DEF",       TOK_DEF,       0 },
    { "POKE",      TOK_POKE,      0 },
    { "CONT",      TOK_CONT,      0 },
    { "OUT",       TOK_OUT,       0 },
    { "LPRINT",    TOK_LPRINT,    0 },
    { "LLIST",     TOK_LLIST,     0 },
    { "WIDTH",     TOK_WIDTH,     0 },
    { "ELSE",      TOK_ELSE,      0 },
    { "TRON",      TOK_TRON,      0 },
    { "TROFF",     TOK_TROFF,     0 },
    { "SWAP",      TOK_SWAP,      0 },
    { "ERASE",     TOK_ERASE,     0 },
    { "EDIT",      TOK_EDIT,      0 },
    { "ERROR",     TOK_ERROR,     0 },
    { "RESUME",    TOK_RESUME,    0 },
    { "DELETE",    TOK_DELETE,    0 },
    { "AUTO",      TOK_AUTO,      0 },
    { "RENUM",     TOK_RENUM,     0 },
    { "DEFSTR",    TOK_DEFSTR,    0 },
    { "DEFINT",    TOK_DEFINT,    0 },
    { "DEFSNG",    TOK_DEFSNG,    0 },
    { "DEFDBL",    TOK_DEFDBL,    0 },
    { "LINE",      TOK_LINE,      0 },
    { "WHILE",     TOK_WHILE,     0 },
    { "WEND",      TOK_WEND,      0 },
    { "CALL",      TOK_CALL,      0 },
    { "WRITE",     TOK_WRITE,     0 },
    { "OPTION",    TOK_OPTION,    0 },
    { "RANDOMIZE", TOK_RANDOMIZE, 0 },
    { "OPEN",      TOK_OPEN,      0 },
    { "CLOSE",     TOK_CLOSE,     0 },
    { "LOAD",      TOK_LOAD,      0 },
    { "MERGE",     TOK_MERGE,     0 },
    { "SAVE",      TOK_SAVE,      0 },
    { "COLOR",     TOK_COLOR,     0 },
    { "CLS",       TOK_CLS,       0 },
    { "MOTOR",     TOK_MOTOR,     0 },
    { "BSAVE",     TOK_BSAVE,     0 },
    { "BLOAD",     TOK_BLOAD,     0 },
    { "SOUND",     TOK_SOUND,     0 },
    { "BEEP",      TOK_BEEP,      0 },
    { "PSET",      TOK_PSET,      0 },
    { "PRESET",    TOK_PRESET,    0 },
    { "SCREEN",    TOK_SCREEN,    0 },
    { "KEY",       TOK_KEY,       0 },
    { "LOCATE",    TOK_LOCATE,    0 },

    /* Non-statement keyword tokens */
    { "TO",        TOK_TO,        0 },
    { "THEN",      TOK_THEN,      0 },
    { "TAB(",      TOK_TAB,       0 },
    { "STEP",      TOK_STEP,      0 },
    { "USR",       TOK_USR,       0 },
    { "FN",        TOK_FN,        0 },
    { "SPC(",      TOK_SPC,       0 },
    { "NOT",       TOK_NOT,       0 },
    { "ERL",       TOK_ERL,       0 },
    { "ERR",       TOK_ERR,       0 },
    { "STRING$",   TOK_STRINGS,   0 },
    { "USING",     TOK_USING,     0 },
    { "INSTR",     TOK_INSTR,     0 },
    { "'",         TOK_SQUOTE,    0 },
    { "VARPTR",    TOK_VARPTR,    0 },
    { "CSRLIN",    TOK_CSRLIN,    0 },
    { "POINT",     TOK_POINT,     0 },
    { "OFF",       TOK_OFF,       0 },
    { "INKEY$",    TOK_INKEYS,    0 },

    /* Operator tokens */
    { ">",         TOK_GT,        0 },
    { "=",         TOK_EQ,        0 },
    { "<",         TOK_LT,        0 },
    { "+",         TOK_PLUS,      0 },
    { "-",         TOK_MINUS,     0 },
    { "*",         TOK_MUL,       0 },
    { "/",         TOK_DIV,       0 },
    { "^",         TOK_POW,       0 },
    { "AND",       TOK_AND,       0 },
    { "OR",        TOK_OR,        0 },
    { "XOR",       TOK_XOR,       0 },
    { "EQV",       TOK_EQV,       0 },
    { "IMP",       TOK_IMP,       0 },
    { "MOD",       TOK_MOD,       0 },
    { "\\",        TOK_IDIV,      0 },

    /* Built-in functions (prefix 0xFF) */
    { "LEFT$",     FUNC_LEFT,     TOK_PREFIX_FF },
    { "RIGHT$",    FUNC_RIGHT,    TOK_PREFIX_FF },
    { "MID$",      FUNC_MID,      TOK_PREFIX_FF },
    { "SGN",       FUNC_SGN,      TOK_PREFIX_FF },
    { "INT",       FUNC_INT,      TOK_PREFIX_FF },
    { "ABS",       FUNC_ABS,      TOK_PREFIX_FF },
    { "SQR",       FUNC_SQR,      TOK_PREFIX_FF },
    { "RND",       FUNC_RND,      TOK_PREFIX_FF },
    { "SIN",       FUNC_SIN,      TOK_PREFIX_FF },
    { "LOG",       FUNC_LOG,      TOK_PREFIX_FF },
    { "EXP",       FUNC_EXP,      TOK_PREFIX_FF },
    { "COS",       FUNC_COS,      TOK_PREFIX_FF },
    { "TAN",       FUNC_TAN,      TOK_PREFIX_FF },
    { "ATN",       FUNC_ATN,      TOK_PREFIX_FF },
    { "FRE",       FUNC_FRE,      TOK_PREFIX_FF },
    { "INP",       FUNC_INP,      TOK_PREFIX_FF },
    { "POS",       FUNC_POS,      TOK_PREFIX_FF },
    { "LEN",       FUNC_LEN,      TOK_PREFIX_FF },
    { "STR$",      FUNC_STR,      TOK_PREFIX_FF },
    { "VAL",       FUNC_VAL,      TOK_PREFIX_FF },
    { "ASC",       FUNC_ASC,      TOK_PREFIX_FF },
    { "CHR$",      FUNC_CHR,      TOK_PREFIX_FF },
    { "PEEK",      FUNC_PEEK,     TOK_PREFIX_FF },
    { "SPACE$",    FUNC_SPACE,    TOK_PREFIX_FF },
    { "OCT$",      FUNC_OCT,      TOK_PREFIX_FF },
    { "HEX$",      FUNC_HEX,      TOK_PREFIX_FF },
    { "LPOS",      FUNC_LPOS,     TOK_PREFIX_FF },
    { "CINT",      FUNC_CINT,     TOK_PREFIX_FF },
    { "CSNG",      FUNC_CSNG,     TOK_PREFIX_FF },
    { "CDBL",      FUNC_CDBL,     TOK_PREFIX_FF },
    { "FIX",       FUNC_FIX,      TOK_PREFIX_FF },
    { "PEN",       FUNC_PEN,      TOK_PREFIX_FF },
    { "STICK",     FUNC_STICK,    TOK_PREFIX_FF },
    { "STRIG",     FUNC_STRIG,    TOK_PREFIX_FF },
    { "EOF",       FUNC_EOF,      TOK_PREFIX_FF },
    { "LOC",       FUNC_LOC,      TOK_PREFIX_FF },
    { "LOF",       FUNC_LOF,      TOK_PREFIX_FF },

    /* Extended statements (prefix 0xFE) */
    { "FILES",     XSTMT_FILES,   TOK_PREFIX_FE },
    { "FIELD",     XSTMT_FIELD,   TOK_PREFIX_FE },
    { "SYSTEM",    XSTMT_SYSTEM,  TOK_PREFIX_FE },
    { "NAME",      XSTMT_NAME,    TOK_PREFIX_FE },
    { "LSET",      XSTMT_LSET,    TOK_PREFIX_FE },
    { "RSET",      XSTMT_RSET,    TOK_PREFIX_FE },
    { "KILL",      XSTMT_KILL,    TOK_PREFIX_FE },
    { "PUT",       XSTMT_PUT,     TOK_PREFIX_FE },
    { "GET",       XSTMT_GET,     TOK_PREFIX_FE },
    { "RESET",     XSTMT_RESET,   TOK_PREFIX_FE },
    { "COMMON",    XSTMT_COMMON,  TOK_PREFIX_FE },
    { "CHAIN",     XSTMT_CHAIN,   TOK_PREFIX_FE },
    { "DATE$",     XSTMT_DATE,    TOK_PREFIX_FE },
    { "TIME$",     XSTMT_TIME,    TOK_PREFIX_FE },
    { "PAINT",     XSTMT_PAINT,   TOK_PREFIX_FE },
    { "COM",       XSTMT_COM,     TOK_PREFIX_FE },
    { "CIRCLE",    XSTMT_CIRCLE,  TOK_PREFIX_FE },
    { "DRAW",      XSTMT_DRAW,    TOK_PREFIX_FE },
    { "PLAY",      XSTMT_PLAY,    TOK_PREFIX_FE },
    { "TIMER",     XSTMT_TIMER,   TOK_PREFIX_FE },
    { "ERDEV",     XSTMT_ERDEV,   TOK_PREFIX_FE },
    { "IOCTL",     XSTMT_IOCTL,   TOK_PREFIX_FE },
    { "CHDIR",     XSTMT_CHDIR,   TOK_PREFIX_FE },
    { "MKDIR",     XSTMT_MKDIR,   TOK_PREFIX_FE },
    { "RMDIR",     XSTMT_RMDIR,   TOK_PREFIX_FE },
    { "SHELL",     XSTMT_SHELL,   TOK_PREFIX_FE },
    { "ENVIRON",   XSTMT_ENVIRON, TOK_PREFIX_FE },
    { "VIEW",      XSTMT_VIEW,    TOK_PREFIX_FE },
    { "WINDOW",    XSTMT_WINDOW,  TOK_PREFIX_FE },
    { "PMAP",      XSTMT_PMAP,    TOK_PREFIX_FE },
    { "PALETTE",   XSTMT_PALETTE, TOK_PREFIX_FE },
    { "LCOPY",     XSTMT_LCOPY,   TOK_PREFIX_FE },
    { "CALLS",     XSTMT_CALLS,   TOK_PREFIX_FE },

    /* Extended functions (prefix 0xFD) */
    { "CVI",       XFUNC_CVI,     TOK_PREFIX_FD },
    { "CVS",       XFUNC_CVS,     TOK_PREFIX_FD },
    { "CVD",       XFUNC_CVD,     TOK_PREFIX_FD },
    { "MKI$",      XFUNC_MKI,     TOK_PREFIX_FD },
    { "MKS$",      XFUNC_MKS,     TOK_PREFIX_FD },
    { "MKD$",      XFUNC_MKD,     TOK_PREFIX_FD },

    { NULL, 0, 0 }
};

int gw_keyword_count = sizeof(gw_keywords) / sizeof(gw_keywords[0]) - 1;

const char *gw_token_name(uint8_t prefix, uint8_t token)
{
    for (int i = 0; gw_keywords[i].name; i++) {
        if (gw_keywords[i].prefix == prefix && gw_keywords[i].token == token)
            return gw_keywords[i].name;
    }
    return NULL;
}
